<?
echo "    <footer class='text-center'>";
echo "        <div class='footer-above'>";
echo "            <div class='container'>";
echo "                <div class='row'>";
echo "                    <div style='font-family: Bavro;     letter-spacing: 3px;' class='lokacja footer-col col-md-4'>";
echo "                        <h3 style='font-family: Bavro'>Location</h3>";
echo "                        <p>Szczecin";
echo "                            <br>Poland</p>";
echo "                    </div>";
echo "                    <div class='footer-col col-md-4'>";
echo "                        <h3 style='font-family: Bavro'>Around the Web</h3>";
echo "                        <ul class='list-inline'>";
echo "                            <li>";
echo "                                <a href='https://www.youtube.com/channel/UCpWZ0V7IryDrwKu9NcbWsRw?view_as=subscriber' role='youtube' class='btn-social btn-outline'><i class='fa fab fa-youtube'></i></a>";
echo "                            </li>";
echo "                            <li>";
echo "                                <a href='https://www.facebook.com/konrad117' class='btn-social btn-outline' role='facebook'><i class='fa fa-fw fa-facebook'></i></a>";
echo "                            </li>";
echo "                            <li>";
echo "                                <a href='https://plus.google.com/u/0/+KonradZając' class='btn-social btn-outline' role='googleplus'><i class='fa fa-fw fa-google-plus'></i></a>";
echo "                            </li>";
echo "                            <li>";
echo "                                <a href='https://twitter.com/konradzajac' class='btn-social btn-outline' role='twitter'><i class='fa fa-fw fa-twitter'></i></a>";
echo "                            </li>";
echo "                            <li>";
echo "                                <a href='https://www.linkedin.com/in/konrad-zając-7b95b587?trk=hp-identity-photo' class='btn-social btn-outline' role='linkedin'><i class='fa fa-fw fa-linkedin'></i></a>";
echo "                            </li>";
echo "                        </ul>";
echo "                    </div>";
echo "                    <div style='font-family: Bavro;     letter-spacing: 3px;' class='lokacja footer-col col-md-4'>";
echo "                        <h3 style='font-family: Bavro'> https <i class='glyphicon glyphicon-lock'></i></h3>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "        <div class='footer-below'>";
echo "            <div class='container'>";
echo "                <div class='row'>";
echo "                    <div class='col-lg-12'>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </footer>";
