<?php
  
            
echo"<table align=\"center\" class=\"table-bordered; col-md-12\" >";
echo"                        <thead>";
echo"                            <td style=\"width:5%\"align=\"center\"    >";
echo"                                # ";
echo"                            </td>";
echo"                            ";
echo"                            <td align=\"center\" class=\"col-md-2\" >";
echo"                                PHP";
echo"                            </td>";
echo"                            <td align=\"center\" class=\"col-md-2\" >";
echo"                                Python";
echo"                            </td>";
echo"                            <td align=\"center\" class=\"col-md-2\" >";
echo"                                C";
echo"                            </td>";
echo"                            <td align=\"center\" class=\"col-md-2\" >";
echo"                                C++";
echo"                            </td>";
echo"                            <td align=\"center\" class=\"col-md-2\" >";
echo"                                Java";
echo"                            </td>";
echo"                        </thead>";
echo"                        <tbody>";
echo"                            <tr>";
echo"                                <td align=\"center\" colspan=\"6\" style=\"color:white; background-color:black\">For 1000 numbers</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\" align=\"center\">1</td><td align=\"center\" align=\"center\">0,053</td><td align=\"center\" align=\"center\">0,095</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\" tyle=\" width:400%\">0,008</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">2</td><td align=\"center\">0,051</td><td align=\"center\">0,091</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,010</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">3</td><td align=\"center\">0,050</td><td align=\"center\">0,091</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,009</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">4</td><td align=\"center\">0,104</td><td align=\"center\">0,092</td><td align=\"center\">0,003</td><td align=\"center\">0,004</td><td align=\"center\">0,008</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">5</td><td align=\"center\">0,052</td><td align=\"center\">0,091</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,009</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">6</td><td align=\"center\">0,965</td><td align=\"center\">0,091</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,010</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">7</td><td align=\"center\">0,053</td><td align=\"center\">0,091</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,010</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">8</td><td align=\"center\">0,052</td><td align=\"center\">0,101</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,008</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">9</td><td align=\"center\">0,053</td><td align=\"center\">0,091</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,009</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">10</td><td align=\"center\">0,052</td><td align=\"center\">0,092</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,010</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">Mean </td><td align=\"center\">  0,0525</td><td align=\"center\">0,091</td><td align=\"center\">0,003</td><td align=\"center\">0,003</td><td align=\"center\">0,009</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\" colspan=\"6\" style=\"color:white; background-color:black\">For 10 000 numbers</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">1</td><td align=\"center\">4,648</td><td align=\"center\">7,750</td><td align=\"center\">0,286</td><td align=\"center\">0,291</td><td align=\"center\">0,405</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">2</td><td align=\"center\">4,783</td><td align=\"center\">7,731</td><td align=\"center\">0,296</td><td align=\"center\">0,289</td><td align=\"center\">0,0359</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">3</td><td align=\"center\">4,665</td><td align=\"center\">7,805</td><td align=\"center\">0,308</td><td align=\"center\">0,291</td><td align=\"center\">0,352</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">4</td><td align=\"center\">4,706</td><td align=\"center\">7,750</td><td align=\"center\">0,286</td><td align=\"center\">0,291</td><td align=\"center\">0,0351</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">5</td><td align=\"center\">4,633</td><td align=\"center\">7,780</td><td align=\"center\">0,288</td><td align=\"center\">0,294</td><td align=\"center\">0,360</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">6</td><td align=\"center\">4,700</td><td align=\"center\">7,759</td><td align=\"center\">0,292</td><td align=\"center\">0,294</td><td align=\"center\">0,355</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">7</td><td align=\"center\">4,682</td><td align=\"center\">7,750</td><td align=\"center\">0,303</td><td align=\"center\">0,293</td><td align=\"center\">0,349</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">8</td><td align=\"center\">4,654</td><td align=\"center\">7,876</td><td align=\"center\">0,301</td><td align=\"center\">0,295</td><td align=\"center\">0,346</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">9</td><td align=\"center\">4,769</td><td align=\"center\">7,805</td><td align=\"center\">0,289</td><td align=\"center\">0,292</td><td align=\"center\">0,350</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">10</td><td align=\"center\">4,772</td><td align=\"center\">7,790</td><td align=\"center\">0,287</td><td align=\"center\">0,298</td><td align=\"center\">0,467</td>";
echo"                            </tr>";
echo"                            <tr>";
echo"                            <td align=\"center\">Mean </td><td align=\"center\">4,691</td><td align=\"center\">7,7695</td><td align=\"center\">0,2905</td><td align=\"center\">0,2925</td><td align=\"center\">0,3535</td>";
echo"                            </tr>";
echo"                            </tbody>";
echo"                            </table>";
