<?
echo "<div class='portfolio-modal modal fade' id='cert_1' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Master's diploma</h2><img src='src/img/jpg/c1.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_2' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>EF Englisch certificate [C1]</h2><img src='src/img/jpg/c2.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_3' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>TOlC Englich [B2]</h2><img src='src/img/jpg/c3.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_4' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>CambridgeEnglisch certificate [B2]</h2><img src='src/img/jpg/c4.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_5' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Goethe Institute [A1]</h2><img src='src/img/jpg/c5.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_6' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Pluralsight IQ HTML5</h2><img src='src/img/jpg/c6.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_7' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Pluralsight IQ Photoshop</h2><img src='src/img/jpg/c7.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_8' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Pluralsight IQ CSS</h2><img src='src/img/jpg/c8.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_9' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Pluralsight IQ jQuery</h2><img src='src/img/jpg/c9.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_10' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Hackatin WAWCODE</h2><img src='src/img/jpg/c10.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_11' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Pluralsight IQ MySQL</h2><img src='src/img/jpg/c11.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
echo "<div class='portfolio-modal modal fade' id='cert_12' tabindex='-1' role='dialog' aria-hidden='true'><div class='modal-content'><div class='close-modal' data-dismiss='modal'><div class='lr'><div class='rl'></div></div></div><div class='container'><div class='row'><div class='col-lg-8 col-lg-offset-2'><div class='modal-body'><h2>Pluralsight IQ JavaScript</h2><img src='src/img/jpg/c12.jpg' class='img-responsive img-centered' alt=''></a></div></div></div></div></div></div>";
